# Generated by Django 2.0 on 2017-12-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group',
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargodepot',
            fields=[
                ('cargo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('height', models.IntegerField()),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('numberofloaders', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'cargodepot',
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_admin_log',
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_session',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('passengers', models.IntegerField(blank=True, null=True)),
                ('timeofarrival', models.TimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('timeofdeparture', models.TimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'flight',
            },
        ),
        migrations.CreateModel(
            name='Gates',
            fields=[
                ('gates_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('throughput', models.BigIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'gates',
            },
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('plane_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('seats', models.BigIntegerField(blank=True, null=True)),
                ('fuelweight', models.BigIntegerField(blank=True, null=True)),
                ('wingspan', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'plane',
            },
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('runway_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('weightallowed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'runway',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('terminal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('passengertraffic', models.BigIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('radarrange', models.BigIntegerField(blank=True, null=True)),
                ('callsign', models.CharField(blank=True, db_column='Callsign', max_length=4, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'terminal',
            },
        ),
    ]
